version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-server:3001
      - EVENT_SERVICE_URL=http://event-server:3002
    depends_on:
      - auth-server
      - event-server
    networks:
      - app-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/auth-db
      - JWT_SECRET=your_secret_key_here
      - JWT_EXPIRATION=1h
    depends_on:
      - mongodb
    networks:
      - app-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/event-db
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
